builds:
  - binary: goserve
    ldflags: "-X github.com/kevingimbel/goserve/main.version={{.Version}} -X github.com/kevingimbel/goserve/main.buildDate={{.Date}} -X github.com/kevingimbel/goserve/main.commit={{.Commit}}"
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  replacements:
    amd64: 64-bit
    darwin: macOS
 
brew:
  github:
    owner: kevingimbel
    name: homebrew-tap
  homepage: https://github.com/kevingimbel/goserve
  description: "Simple static file server written in Go"
